name: scrobblenaut
description: A deadly simple LastFM API Wrapper for Dart. So deadly simple that it's gonna hit the mark.
version: 3.0.0
homepage: https://github.com/Nebulino/Scrobblenaut
issue_tracker: https://github.com/Nebulino/Scrobblenaut/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1
  json_annotation: ^4.8.1
  convert: ^3.0.2
  dio: ^5.2.1+1
  crypto: ^3.0.2
  xml: ^6.3.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.5
  json_serializable: ^6.7.0
  build_runner: ^2.4.4
